Repository Roadmunk/eslint-config-roadmunk, pull requests merged in 2019-03, with the labels that each got.

#20 DB-11 Added rule for checking if views package being imported via 'require'
  index.js
  package-lock.json
  package.json
Labels: α/done, β/progress

#21 DB-11 use 'warn' not 'warning'
  index.js
  package.json
Labels: α/done, β/done

#22 Add rule to prevent use of log.info
  index.js
  package-lock.json
  package.json
Labels: α/done, β/done

#23 Feature/no require path js
  index.js
  package-lock.json
  package.json
Labels: B/done, a/done
